// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: plugin/proto/plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginService_GetProviders_FullMethodName          = "/plugin.PluginService/GetProviders"
	PluginService_GetProviderDescriptor_FullMethodName = "/plugin.PluginService/GetProviderDescriptor"
	PluginService_ConfigureProvider_FullMethodName     = "/plugin.PluginService/ConfigureProvider"
	PluginService_ExecuteProvider_FullMethodName       = "/plugin.PluginService/ExecuteProvider"
	PluginService_ExecuteProviderStream_FullMethodName = "/plugin.PluginService/ExecuteProviderStream"
	PluginService_DescribeWhatIf_FullMethodName        = "/plugin.PluginService/DescribeWhatIf"
	PluginService_ExtractDependencies_FullMethodName   = "/plugin.PluginService/ExtractDependencies"
	PluginService_StopProvider_FullMethodName          = "/plugin.PluginService/StopProvider"
)

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginService is the provider plugin service.
type PluginServiceClient interface {
	// GetProviders returns all providers exposed by this plugin
	GetProviders(ctx context.Context, in *GetProvidersRequest, opts ...grpc.CallOption) (*GetProvidersResponse, error)
	// GetProviderDescriptor returns metadata for a specific provider
	GetProviderDescriptor(ctx context.Context, in *GetProviderDescriptorRequest, opts ...grpc.CallOption) (*GetProviderDescriptorResponse, error)
	// ConfigureProvider sends host-side configuration to a provider once after
	// plugin load. Providers store this internally for subsequent Execute calls.
	ConfigureProvider(ctx context.Context, in *ConfigureProviderRequest, opts ...grpc.CallOption) (*ConfigureProviderResponse, error)
	// ExecuteProvider executes a provider
	ExecuteProvider(ctx context.Context, in *ExecuteProviderRequest, opts ...grpc.CallOption) (*ExecuteProviderResponse, error)
	// ExecuteProviderStream executes a provider that produces incremental output.
	// The server sends zero or more OutputChunk messages followed by exactly one
	// Result message.
	ExecuteProviderStream(ctx context.Context, in *ExecuteProviderRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteProviderStreamChunk], error)
	// DescribeWhatIf returns a human-readable description of what the provider
	// would do with the given inputs, without executing.
	DescribeWhatIf(ctx context.Context, in *DescribeWhatIfRequest, opts ...grpc.CallOption) (*DescribeWhatIfResponse, error)
	// ExtractDependencies returns resolver dependency names from the provider's
	// inputs. Called during dependency graph construction. Plugins that do not
	// implement custom extraction should return an empty list (the host falls
	// back to generic extraction).
	ExtractDependencies(ctx context.Context, in *ExtractDependenciesRequest, opts ...grpc.CallOption) (*ExtractDependenciesResponse, error)
	// StopProvider requests graceful shutdown of a running provider execution.
	// The host calls this when the user cancels an operation (e.g. Ctrl+C).
	// Plugins should abort in-flight work and return promptly.
	StopProvider(ctx context.Context, in *StopProviderRequest, opts ...grpc.CallOption) (*StopProviderResponse, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) GetProviders(ctx context.Context, in *GetProvidersRequest, opts ...grpc.CallOption) (*GetProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProvidersResponse)
	err := c.cc.Invoke(ctx, PluginService_GetProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) GetProviderDescriptor(ctx context.Context, in *GetProviderDescriptorRequest, opts ...grpc.CallOption) (*GetProviderDescriptorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProviderDescriptorResponse)
	err := c.cc.Invoke(ctx, PluginService_GetProviderDescriptor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) ConfigureProvider(ctx context.Context, in *ConfigureProviderRequest, opts ...grpc.CallOption) (*ConfigureProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureProviderResponse)
	err := c.cc.Invoke(ctx, PluginService_ConfigureProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) ExecuteProvider(ctx context.Context, in *ExecuteProviderRequest, opts ...grpc.CallOption) (*ExecuteProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteProviderResponse)
	err := c.cc.Invoke(ctx, PluginService_ExecuteProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) ExecuteProviderStream(ctx context.Context, in *ExecuteProviderRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteProviderStreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PluginService_ServiceDesc.Streams[0], PluginService_ExecuteProviderStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteProviderRequest, ExecuteProviderStreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginService_ExecuteProviderStreamClient = grpc.ServerStreamingClient[ExecuteProviderStreamChunk]

func (c *pluginServiceClient) DescribeWhatIf(ctx context.Context, in *DescribeWhatIfRequest, opts ...grpc.CallOption) (*DescribeWhatIfResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeWhatIfResponse)
	err := c.cc.Invoke(ctx, PluginService_DescribeWhatIf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) ExtractDependencies(ctx context.Context, in *ExtractDependenciesRequest, opts ...grpc.CallOption) (*ExtractDependenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractDependenciesResponse)
	err := c.cc.Invoke(ctx, PluginService_ExtractDependencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) StopProvider(ctx context.Context, in *StopProviderRequest, opts ...grpc.CallOption) (*StopProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopProviderResponse)
	err := c.cc.Invoke(ctx, PluginService_StopProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility.
//
// PluginService is the provider plugin service.
type PluginServiceServer interface {
	// GetProviders returns all providers exposed by this plugin
	GetProviders(context.Context, *GetProvidersRequest) (*GetProvidersResponse, error)
	// GetProviderDescriptor returns metadata for a specific provider
	GetProviderDescriptor(context.Context, *GetProviderDescriptorRequest) (*GetProviderDescriptorResponse, error)
	// ConfigureProvider sends host-side configuration to a provider once after
	// plugin load. Providers store this internally for subsequent Execute calls.
	ConfigureProvider(context.Context, *ConfigureProviderRequest) (*ConfigureProviderResponse, error)
	// ExecuteProvider executes a provider
	ExecuteProvider(context.Context, *ExecuteProviderRequest) (*ExecuteProviderResponse, error)
	// ExecuteProviderStream executes a provider that produces incremental output.
	// The server sends zero or more OutputChunk messages followed by exactly one
	// Result message.
	ExecuteProviderStream(*ExecuteProviderRequest, grpc.ServerStreamingServer[ExecuteProviderStreamChunk]) error
	// DescribeWhatIf returns a human-readable description of what the provider
	// would do with the given inputs, without executing.
	DescribeWhatIf(context.Context, *DescribeWhatIfRequest) (*DescribeWhatIfResponse, error)
	// ExtractDependencies returns resolver dependency names from the provider's
	// inputs. Called during dependency graph construction. Plugins that do not
	// implement custom extraction should return an empty list (the host falls
	// back to generic extraction).
	ExtractDependencies(context.Context, *ExtractDependenciesRequest) (*ExtractDependenciesResponse, error)
	// StopProvider requests graceful shutdown of a running provider execution.
	// The host calls this when the user cancels an operation (e.g. Ctrl+C).
	// Plugins should abort in-flight work and return promptly.
	StopProvider(context.Context, *StopProviderRequest) (*StopProviderResponse, error)
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServiceServer struct{}

func (UnimplementedPluginServiceServer) GetProviders(context.Context, *GetProvidersRequest) (*GetProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProviders not implemented")
}
func (UnimplementedPluginServiceServer) GetProviderDescriptor(context.Context, *GetProviderDescriptorRequest) (*GetProviderDescriptorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProviderDescriptor not implemented")
}
func (UnimplementedPluginServiceServer) ConfigureProvider(context.Context, *ConfigureProviderRequest) (*ConfigureProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureProvider not implemented")
}
func (UnimplementedPluginServiceServer) ExecuteProvider(context.Context, *ExecuteProviderRequest) (*ExecuteProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteProvider not implemented")
}
func (UnimplementedPluginServiceServer) ExecuteProviderStream(*ExecuteProviderRequest, grpc.ServerStreamingServer[ExecuteProviderStreamChunk]) error {
	return status.Error(codes.Unimplemented, "method ExecuteProviderStream not implemented")
}
func (UnimplementedPluginServiceServer) DescribeWhatIf(context.Context, *DescribeWhatIfRequest) (*DescribeWhatIfResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeWhatIf not implemented")
}
func (UnimplementedPluginServiceServer) ExtractDependencies(context.Context, *ExtractDependenciesRequest) (*ExtractDependenciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractDependencies not implemented")
}
func (UnimplementedPluginServiceServer) StopProvider(context.Context, *StopProviderRequest) (*StopProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopProvider not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}
func (UnimplementedPluginServiceServer) testEmbeddedByValue()                       {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_GetProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetProviders(ctx, req.(*GetProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_GetProviderDescriptor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderDescriptorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetProviderDescriptor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetProviderDescriptor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetProviderDescriptor(ctx, req.(*GetProviderDescriptorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_ConfigureProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).ConfigureProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_ConfigureProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).ConfigureProvider(ctx, req.(*ConfigureProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_ExecuteProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).ExecuteProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_ExecuteProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).ExecuteProvider(ctx, req.(*ExecuteProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_ExecuteProviderStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteProviderRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PluginServiceServer).ExecuteProviderStream(m, &grpc.GenericServerStream[ExecuteProviderRequest, ExecuteProviderStreamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginService_ExecuteProviderStreamServer = grpc.ServerStreamingServer[ExecuteProviderStreamChunk]

func _PluginService_DescribeWhatIf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeWhatIfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).DescribeWhatIf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_DescribeWhatIf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).DescribeWhatIf(ctx, req.(*DescribeWhatIfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_ExtractDependencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractDependenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).ExtractDependencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_ExtractDependencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).ExtractDependencies(ctx, req.(*ExtractDependenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_StopProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).StopProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_StopProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).StopProvider(ctx, req.(*StopProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProviders",
			Handler:    _PluginService_GetProviders_Handler,
		},
		{
			MethodName: "GetProviderDescriptor",
			Handler:    _PluginService_GetProviderDescriptor_Handler,
		},
		{
			MethodName: "ConfigureProvider",
			Handler:    _PluginService_ConfigureProvider_Handler,
		},
		{
			MethodName: "ExecuteProvider",
			Handler:    _PluginService_ExecuteProvider_Handler,
		},
		{
			MethodName: "DescribeWhatIf",
			Handler:    _PluginService_DescribeWhatIf_Handler,
		},
		{
			MethodName: "ExtractDependencies",
			Handler:    _PluginService_ExtractDependencies_Handler,
		},
		{
			MethodName: "StopProvider",
			Handler:    _PluginService_StopProvider_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteProviderStream",
			Handler:       _PluginService_ExecuteProviderStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin/proto/plugin.proto",
}

const (
	HostService_GetSecret_FullMethodName        = "/plugin.HostService/GetSecret"
	HostService_SetSecret_FullMethodName        = "/plugin.HostService/SetSecret"
	HostService_DeleteSecret_FullMethodName     = "/plugin.HostService/DeleteSecret"
	HostService_ListSecrets_FullMethodName      = "/plugin.HostService/ListSecrets"
	HostService_GetAuthIdentity_FullMethodName  = "/plugin.HostService/GetAuthIdentity"
	HostService_ListAuthHandlers_FullMethodName = "/plugin.HostService/ListAuthHandlers"
	HostService_GetAuthToken_FullMethodName     = "/plugin.HostService/GetAuthToken"
	HostService_GetAuthGroups_FullMethodName    = "/plugin.HostService/GetAuthGroups"
)

// HostServiceClient is the client API for HostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostService is a callback service that plugins can invoke on the host.
// The host registers this service via the go-plugin GRPCBroker, allowing
// plugins to access host-side resources that cannot be serialized.
type HostServiceClient interface {
	// GetSecret retrieves a secret value from the host's secret store.
	GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error)
	// SetSecret stores a secret value in the host's secret store.
	SetSecret(ctx context.Context, in *SetSecretRequest, opts ...grpc.CallOption) (*SetSecretResponse, error)
	// DeleteSecret removes a secret from the host's secret store.
	DeleteSecret(ctx context.Context, in *DeleteSecretRequest, opts ...grpc.CallOption) (*DeleteSecretResponse, error)
	// ListSecrets lists secret names from the host's secret store.
	ListSecrets(ctx context.Context, in *ListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error)
	// GetAuthIdentity retrieves identity claims from the host's auth registry.
	GetAuthIdentity(ctx context.Context, in *GetAuthIdentityRequest, opts ...grpc.CallOption) (*GetAuthIdentityResponse, error)
	// ListAuthHandlers lists available auth handlers on the host.
	ListAuthHandlers(ctx context.Context, in *ListAuthHandlersRequest, opts ...grpc.CallOption) (*ListAuthHandlersResponse, error)
	// GetAuthToken retrieves a valid access token from the host's auth registry.
	// Plugins use this for authenticated HTTP requests and token refresh on 401.
	GetAuthToken(ctx context.Context, in *GetAuthTokenRequest, opts ...grpc.CallOption) (*GetAuthTokenResponse, error)
	// GetAuthGroups retrieves group memberships for the authenticated user.
	// Only handlers that implement group queries (e.g. Entra) will return results.
	GetAuthGroups(ctx context.Context, in *GetAuthGroupsRequest, opts ...grpc.CallOption) (*GetAuthGroupsResponse, error)
}

type hostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostServiceClient(cc grpc.ClientConnInterface) HostServiceClient {
	return &hostServiceClient{cc}
}

func (c *hostServiceClient) GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecretResponse)
	err := c.cc.Invoke(ctx, HostService_GetSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) SetSecret(ctx context.Context, in *SetSecretRequest, opts ...grpc.CallOption) (*SetSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSecretResponse)
	err := c.cc.Invoke(ctx, HostService_SetSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) DeleteSecret(ctx context.Context, in *DeleteSecretRequest, opts ...grpc.CallOption) (*DeleteSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSecretResponse)
	err := c.cc.Invoke(ctx, HostService_DeleteSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) ListSecrets(ctx context.Context, in *ListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSecretsResponse)
	err := c.cc.Invoke(ctx, HostService_ListSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) GetAuthIdentity(ctx context.Context, in *GetAuthIdentityRequest, opts ...grpc.CallOption) (*GetAuthIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthIdentityResponse)
	err := c.cc.Invoke(ctx, HostService_GetAuthIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) ListAuthHandlers(ctx context.Context, in *ListAuthHandlersRequest, opts ...grpc.CallOption) (*ListAuthHandlersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuthHandlersResponse)
	err := c.cc.Invoke(ctx, HostService_ListAuthHandlers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) GetAuthToken(ctx context.Context, in *GetAuthTokenRequest, opts ...grpc.CallOption) (*GetAuthTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthTokenResponse)
	err := c.cc.Invoke(ctx, HostService_GetAuthToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) GetAuthGroups(ctx context.Context, in *GetAuthGroupsRequest, opts ...grpc.CallOption) (*GetAuthGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthGroupsResponse)
	err := c.cc.Invoke(ctx, HostService_GetAuthGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServiceServer is the server API for HostService service.
// All implementations must embed UnimplementedHostServiceServer
// for forward compatibility.
//
// HostService is a callback service that plugins can invoke on the host.
// The host registers this service via the go-plugin GRPCBroker, allowing
// plugins to access host-side resources that cannot be serialized.
type HostServiceServer interface {
	// GetSecret retrieves a secret value from the host's secret store.
	GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error)
	// SetSecret stores a secret value in the host's secret store.
	SetSecret(context.Context, *SetSecretRequest) (*SetSecretResponse, error)
	// DeleteSecret removes a secret from the host's secret store.
	DeleteSecret(context.Context, *DeleteSecretRequest) (*DeleteSecretResponse, error)
	// ListSecrets lists secret names from the host's secret store.
	ListSecrets(context.Context, *ListSecretsRequest) (*ListSecretsResponse, error)
	// GetAuthIdentity retrieves identity claims from the host's auth registry.
	GetAuthIdentity(context.Context, *GetAuthIdentityRequest) (*GetAuthIdentityResponse, error)
	// ListAuthHandlers lists available auth handlers on the host.
	ListAuthHandlers(context.Context, *ListAuthHandlersRequest) (*ListAuthHandlersResponse, error)
	// GetAuthToken retrieves a valid access token from the host's auth registry.
	// Plugins use this for authenticated HTTP requests and token refresh on 401.
	GetAuthToken(context.Context, *GetAuthTokenRequest) (*GetAuthTokenResponse, error)
	// GetAuthGroups retrieves group memberships for the authenticated user.
	// Only handlers that implement group queries (e.g. Entra) will return results.
	GetAuthGroups(context.Context, *GetAuthGroupsRequest) (*GetAuthGroupsResponse, error)
	mustEmbedUnimplementedHostServiceServer()
}

// UnimplementedHostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostServiceServer struct{}

func (UnimplementedHostServiceServer) GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecret not implemented")
}
func (UnimplementedHostServiceServer) SetSecret(context.Context, *SetSecretRequest) (*SetSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSecret not implemented")
}
func (UnimplementedHostServiceServer) DeleteSecret(context.Context, *DeleteSecretRequest) (*DeleteSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSecret not implemented")
}
func (UnimplementedHostServiceServer) ListSecrets(context.Context, *ListSecretsRequest) (*ListSecretsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSecrets not implemented")
}
func (UnimplementedHostServiceServer) GetAuthIdentity(context.Context, *GetAuthIdentityRequest) (*GetAuthIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthIdentity not implemented")
}
func (UnimplementedHostServiceServer) ListAuthHandlers(context.Context, *ListAuthHandlersRequest) (*ListAuthHandlersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAuthHandlers not implemented")
}
func (UnimplementedHostServiceServer) GetAuthToken(context.Context, *GetAuthTokenRequest) (*GetAuthTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthToken not implemented")
}
func (UnimplementedHostServiceServer) GetAuthGroups(context.Context, *GetAuthGroupsRequest) (*GetAuthGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthGroups not implemented")
}
func (UnimplementedHostServiceServer) mustEmbedUnimplementedHostServiceServer() {}
func (UnimplementedHostServiceServer) testEmbeddedByValue()                     {}

// UnsafeHostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServiceServer will
// result in compilation errors.
type UnsafeHostServiceServer interface {
	mustEmbedUnimplementedHostServiceServer()
}

func RegisterHostServiceServer(s grpc.ServiceRegistrar, srv HostServiceServer) {
	// If the following call panics, it indicates UnimplementedHostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostService_ServiceDesc, srv)
}

func _HostService_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_GetSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).GetSecret(ctx, req.(*GetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_SetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).SetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_SetSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).SetSecret(ctx, req.(*SetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_DeleteSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).DeleteSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_DeleteSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).DeleteSecret(ctx, req.(*DeleteSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_ListSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).ListSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_ListSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).ListSecrets(ctx, req.(*ListSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_GetAuthIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).GetAuthIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_GetAuthIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).GetAuthIdentity(ctx, req.(*GetAuthIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_ListAuthHandlers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuthHandlersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).ListAuthHandlers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_ListAuthHandlers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).ListAuthHandlers(ctx, req.(*ListAuthHandlersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_GetAuthToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).GetAuthToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_GetAuthToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).GetAuthToken(ctx, req.(*GetAuthTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_GetAuthGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).GetAuthGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_GetAuthGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).GetAuthGroups(ctx, req.(*GetAuthGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostService_ServiceDesc is the grpc.ServiceDesc for HostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.HostService",
	HandlerType: (*HostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSecret",
			Handler:    _HostService_GetSecret_Handler,
		},
		{
			MethodName: "SetSecret",
			Handler:    _HostService_SetSecret_Handler,
		},
		{
			MethodName: "DeleteSecret",
			Handler:    _HostService_DeleteSecret_Handler,
		},
		{
			MethodName: "ListSecrets",
			Handler:    _HostService_ListSecrets_Handler,
		},
		{
			MethodName: "GetAuthIdentity",
			Handler:    _HostService_GetAuthIdentity_Handler,
		},
		{
			MethodName: "ListAuthHandlers",
			Handler:    _HostService_ListAuthHandlers_Handler,
		},
		{
			MethodName: "GetAuthToken",
			Handler:    _HostService_GetAuthToken_Handler,
		},
		{
			MethodName: "GetAuthGroups",
			Handler:    _HostService_GetAuthGroups_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/proto/plugin.proto",
}

const (
	AuthHandlerService_GetAuthHandlers_FullMethodName      = "/plugin.AuthHandlerService/GetAuthHandlers"
	AuthHandlerService_ConfigureAuthHandler_FullMethodName = "/plugin.AuthHandlerService/ConfigureAuthHandler"
	AuthHandlerService_Login_FullMethodName                = "/plugin.AuthHandlerService/Login"
	AuthHandlerService_Logout_FullMethodName               = "/plugin.AuthHandlerService/Logout"
	AuthHandlerService_GetStatus_FullMethodName            = "/plugin.AuthHandlerService/GetStatus"
	AuthHandlerService_GetToken_FullMethodName             = "/plugin.AuthHandlerService/GetToken"
	AuthHandlerService_ListCachedTokens_FullMethodName     = "/plugin.AuthHandlerService/ListCachedTokens"
	AuthHandlerService_PurgeExpiredTokens_FullMethodName   = "/plugin.AuthHandlerService/PurgeExpiredTokens"
	AuthHandlerService_StopAuthHandler_FullMethodName      = "/plugin.AuthHandlerService/StopAuthHandler"
)

// AuthHandlerServiceClient is the client API for AuthHandlerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthHandlerService is the auth handler plugin service.
type AuthHandlerServiceClient interface {
	// GetAuthHandlers returns metadata for all auth handlers exposed by this plugin.
	GetAuthHandlers(ctx context.Context, in *GetAuthHandlersRequest, opts ...grpc.CallOption) (*GetAuthHandlersResponse, error)
	// ConfigureAuthHandler sends host-side configuration to the plugin once after load.
	ConfigureAuthHandler(ctx context.Context, in *ConfigureAuthHandlerRequest, opts ...grpc.CallOption) (*ConfigureAuthHandlerResponse, error)
	// Login initiates authentication. Returns a stream: zero or more DeviceCodePrompt
	// messages followed by exactly one LoginResult message.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LoginStreamMessage], error)
	// Logout clears stored credentials for the named handler.
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	// GetStatus returns the current authentication status.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// GetToken returns a valid access token.
	GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error)
	// ListCachedTokens enumerates cached tokens for the named handler.
	ListCachedTokens(ctx context.Context, in *ListCachedTokensRequest, opts ...grpc.CallOption) (*ListCachedTokensResponse, error)
	// PurgeExpiredTokens removes expired tokens for the named handler.
	PurgeExpiredTokens(ctx context.Context, in *PurgeExpiredTokensRequest, opts ...grpc.CallOption) (*PurgeExpiredTokensResponse, error)
	// StopAuthHandler requests graceful shutdown of a running auth handler operation.
	// handler_name may be empty to stop all handlers.
	StopAuthHandler(ctx context.Context, in *StopAuthHandlerRequest, opts ...grpc.CallOption) (*StopAuthHandlerResponse, error)
}

type authHandlerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthHandlerServiceClient(cc grpc.ClientConnInterface) AuthHandlerServiceClient {
	return &authHandlerServiceClient{cc}
}

func (c *authHandlerServiceClient) GetAuthHandlers(ctx context.Context, in *GetAuthHandlersRequest, opts ...grpc.CallOption) (*GetAuthHandlersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthHandlersResponse)
	err := c.cc.Invoke(ctx, AuthHandlerService_GetAuthHandlers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authHandlerServiceClient) ConfigureAuthHandler(ctx context.Context, in *ConfigureAuthHandlerRequest, opts ...grpc.CallOption) (*ConfigureAuthHandlerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureAuthHandlerResponse)
	err := c.cc.Invoke(ctx, AuthHandlerService_ConfigureAuthHandler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authHandlerServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LoginStreamMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AuthHandlerService_ServiceDesc.Streams[0], AuthHandlerService_Login_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LoginRequest, LoginStreamMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuthHandlerService_LoginClient = grpc.ServerStreamingClient[LoginStreamMessage]

func (c *authHandlerServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, AuthHandlerService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authHandlerServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, AuthHandlerService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authHandlerServiceClient) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTokenResponse)
	err := c.cc.Invoke(ctx, AuthHandlerService_GetToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authHandlerServiceClient) ListCachedTokens(ctx context.Context, in *ListCachedTokensRequest, opts ...grpc.CallOption) (*ListCachedTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCachedTokensResponse)
	err := c.cc.Invoke(ctx, AuthHandlerService_ListCachedTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authHandlerServiceClient) PurgeExpiredTokens(ctx context.Context, in *PurgeExpiredTokensRequest, opts ...grpc.CallOption) (*PurgeExpiredTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurgeExpiredTokensResponse)
	err := c.cc.Invoke(ctx, AuthHandlerService_PurgeExpiredTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authHandlerServiceClient) StopAuthHandler(ctx context.Context, in *StopAuthHandlerRequest, opts ...grpc.CallOption) (*StopAuthHandlerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopAuthHandlerResponse)
	err := c.cc.Invoke(ctx, AuthHandlerService_StopAuthHandler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthHandlerServiceServer is the server API for AuthHandlerService service.
// All implementations must embed UnimplementedAuthHandlerServiceServer
// for forward compatibility.
//
// AuthHandlerService is the auth handler plugin service.
type AuthHandlerServiceServer interface {
	// GetAuthHandlers returns metadata for all auth handlers exposed by this plugin.
	GetAuthHandlers(context.Context, *GetAuthHandlersRequest) (*GetAuthHandlersResponse, error)
	// ConfigureAuthHandler sends host-side configuration to the plugin once after load.
	ConfigureAuthHandler(context.Context, *ConfigureAuthHandlerRequest) (*ConfigureAuthHandlerResponse, error)
	// Login initiates authentication. Returns a stream: zero or more DeviceCodePrompt
	// messages followed by exactly one LoginResult message.
	Login(*LoginRequest, grpc.ServerStreamingServer[LoginStreamMessage]) error
	// Logout clears stored credentials for the named handler.
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	// GetStatus returns the current authentication status.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// GetToken returns a valid access token.
	GetToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error)
	// ListCachedTokens enumerates cached tokens for the named handler.
	ListCachedTokens(context.Context, *ListCachedTokensRequest) (*ListCachedTokensResponse, error)
	// PurgeExpiredTokens removes expired tokens for the named handler.
	PurgeExpiredTokens(context.Context, *PurgeExpiredTokensRequest) (*PurgeExpiredTokensResponse, error)
	// StopAuthHandler requests graceful shutdown of a running auth handler operation.
	// handler_name may be empty to stop all handlers.
	StopAuthHandler(context.Context, *StopAuthHandlerRequest) (*StopAuthHandlerResponse, error)
	mustEmbedUnimplementedAuthHandlerServiceServer()
}

// UnimplementedAuthHandlerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthHandlerServiceServer struct{}

func (UnimplementedAuthHandlerServiceServer) GetAuthHandlers(context.Context, *GetAuthHandlersRequest) (*GetAuthHandlersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthHandlers not implemented")
}
func (UnimplementedAuthHandlerServiceServer) ConfigureAuthHandler(context.Context, *ConfigureAuthHandlerRequest) (*ConfigureAuthHandlerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureAuthHandler not implemented")
}
func (UnimplementedAuthHandlerServiceServer) Login(*LoginRequest, grpc.ServerStreamingServer[LoginStreamMessage]) error {
	return status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthHandlerServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAuthHandlerServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedAuthHandlerServiceServer) GetToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetToken not implemented")
}
func (UnimplementedAuthHandlerServiceServer) ListCachedTokens(context.Context, *ListCachedTokensRequest) (*ListCachedTokensResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCachedTokens not implemented")
}
func (UnimplementedAuthHandlerServiceServer) PurgeExpiredTokens(context.Context, *PurgeExpiredTokensRequest) (*PurgeExpiredTokensResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PurgeExpiredTokens not implemented")
}
func (UnimplementedAuthHandlerServiceServer) StopAuthHandler(context.Context, *StopAuthHandlerRequest) (*StopAuthHandlerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopAuthHandler not implemented")
}
func (UnimplementedAuthHandlerServiceServer) mustEmbedUnimplementedAuthHandlerServiceServer() {}
func (UnimplementedAuthHandlerServiceServer) testEmbeddedByValue()                            {}

// UnsafeAuthHandlerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthHandlerServiceServer will
// result in compilation errors.
type UnsafeAuthHandlerServiceServer interface {
	mustEmbedUnimplementedAuthHandlerServiceServer()
}

func RegisterAuthHandlerServiceServer(s grpc.ServiceRegistrar, srv AuthHandlerServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthHandlerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthHandlerService_ServiceDesc, srv)
}

func _AuthHandlerService_GetAuthHandlers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthHandlersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthHandlerServiceServer).GetAuthHandlers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthHandlerService_GetAuthHandlers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthHandlerServiceServer).GetAuthHandlers(ctx, req.(*GetAuthHandlersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthHandlerService_ConfigureAuthHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureAuthHandlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthHandlerServiceServer).ConfigureAuthHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthHandlerService_ConfigureAuthHandler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthHandlerServiceServer).ConfigureAuthHandler(ctx, req.(*ConfigureAuthHandlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthHandlerService_Login_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LoginRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuthHandlerServiceServer).Login(m, &grpc.GenericServerStream[LoginRequest, LoginStreamMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuthHandlerService_LoginServer = grpc.ServerStreamingServer[LoginStreamMessage]

func _AuthHandlerService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthHandlerServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthHandlerService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthHandlerServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthHandlerService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthHandlerServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthHandlerService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthHandlerServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthHandlerService_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthHandlerServiceServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthHandlerService_GetToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthHandlerServiceServer).GetToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthHandlerService_ListCachedTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCachedTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthHandlerServiceServer).ListCachedTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthHandlerService_ListCachedTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthHandlerServiceServer).ListCachedTokens(ctx, req.(*ListCachedTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthHandlerService_PurgeExpiredTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeExpiredTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthHandlerServiceServer).PurgeExpiredTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthHandlerService_PurgeExpiredTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthHandlerServiceServer).PurgeExpiredTokens(ctx, req.(*PurgeExpiredTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthHandlerService_StopAuthHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopAuthHandlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthHandlerServiceServer).StopAuthHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthHandlerService_StopAuthHandler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthHandlerServiceServer).StopAuthHandler(ctx, req.(*StopAuthHandlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthHandlerService_ServiceDesc is the grpc.ServiceDesc for AuthHandlerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthHandlerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.AuthHandlerService",
	HandlerType: (*AuthHandlerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAuthHandlers",
			Handler:    _AuthHandlerService_GetAuthHandlers_Handler,
		},
		{
			MethodName: "ConfigureAuthHandler",
			Handler:    _AuthHandlerService_ConfigureAuthHandler_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AuthHandlerService_Logout_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _AuthHandlerService_GetStatus_Handler,
		},
		{
			MethodName: "GetToken",
			Handler:    _AuthHandlerService_GetToken_Handler,
		},
		{
			MethodName: "ListCachedTokens",
			Handler:    _AuthHandlerService_ListCachedTokens_Handler,
		},
		{
			MethodName: "PurgeExpiredTokens",
			Handler:    _AuthHandlerService_PurgeExpiredTokens_Handler,
		},
		{
			MethodName: "StopAuthHandler",
			Handler:    _AuthHandlerService_StopAuthHandler_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Login",
			Handler:       _AuthHandlerService_Login_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin/proto/plugin.proto",
}
